### ISSUE TITLE
Option 'quiet' is actually supposed to be 'silent'

### ISSUE THREAD

**Issue by TrevorJTClarke** [leo/gulp-refresh#1]
I was unable to get quiet to work, however adding `silent: true` worked.

*NOTE:* this is a ticket moved from gulp-livereload

**Comment by leo** [comment]
After checking the code and testing it a few times, I came to the conclusion that `quiet` works, but `silent` however doesn't. Also, the word `silent` isn't even part of the code, so it's probably related to your own setup, rather than the plugin.

Regarding `quiet`: Could it be possible that you've tried `quiet: false` instead of `quiet: true`?

**Comment by TrevorJTClarke** [comment]
Ah interesting. I did try quiet: true, however it didnt work then. I remember finding the "silent" word from somewhere (another source the task relies upon??), and the task didnt surface the quiet correctly. If its working for you, go ahead an close. :)
If you are planning on maintaining this, ill switch our projects over here.
thanks!!

**Comment by leo** [comment]
@TrevorJTClarke Okay! :blush:

> If you are planning on maintaining this, ill switch our projects over here.

Yep, I'm maintaining from now on. Sounds like an awesome idea!
